// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vault} from '../models';

export function AnalyseEnvForVault(arg1:string,arg2:string,arg3:string):Promise<main.VaultEnvAnalysis>;

export function AnalyseEnvImport(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ImportAnalysis>;

export function ApplyEnvValues(arg1:string,arg2:string,arg3:Record<string, string>,arg4:Array<string>):Promise<vault.Vault>;

export function BackupVaults(arg1:string,arg2:string):Promise<string>;

export function ChooseBackupSource():Promise<string>;

export function ChooseBackupTarget():Promise<string>;

export function ChooseEnvFile(arg1:string):Promise<main.PickedFile>;

export function ChooseVaultIcon():Promise<string>;

export function CreateVault(arg1:string,arg2:string):Promise<vault.Vault>;

export function CreateVaultFromImport(arg1:string,arg2:string,arg3:string,arg4:Array<main.ImportEntry>):Promise<vault.Vault>;

export function DeleteVault(arg1:string):Promise<void>;

export function GetVault(arg1:string):Promise<vault.Vault>;

export function Greet(arg1:string):Promise<string>;

export function ListVaults():Promise<Array<vault.Vault>>;

export function MinBackupPassphraseLength():Promise<number>;

export function RestoreVaults(arg1:string,arg2:string,arg3:boolean):Promise<main.RestoreResult>;

export function StartupError():Promise<string>;

export function UpdateVault(arg1:vault.Vault):Promise<void>;
