// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseVaultIcon() {
  return window['go']['main']['App']['ChooseVaultIcon']();
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function DeleteVault(arg1) {
  return window['go']['main']['App']['DeleteVault'](arg1);
}

export function GetVault(arg1) {
  return window['go']['main']['App']['GetVault'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListVaults() {
  return window['go']['main']['App']['ListVaults']();
}

export function UpdateVault(arg1) {
  return window['go']['main']['App']['UpdateVault'](arg1);
}
