// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyseEnvForVault(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyseEnvForVault'](arg1, arg2, arg3);
}

export function AnalyseEnvImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyseEnvImport'](arg1, arg2, arg3, arg4);
}

export function ApplyEnvValues(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyEnvValues'](arg1, arg2, arg3, arg4);
}

export function BackupVaults(arg1, arg2) {
  return window['go']['main']['App']['BackupVaults'](arg1, arg2);
}

export function ChooseBackupSource() {
  return window['go']['main']['App']['ChooseBackupSource']();
}

export function ChooseBackupTarget() {
  return window['go']['main']['App']['ChooseBackupTarget']();
}

export function ChooseEnvFile(arg1) {
  return window['go']['main']['App']['ChooseEnvFile'](arg1);
}

export function ChooseVaultIcon() {
  return window['go']['main']['App']['ChooseVaultIcon']();
}

export function CreateVault(arg1, arg2) {
  return window['go']['main']['App']['CreateVault'](arg1, arg2);
}

export function CreateVaultFromImport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateVaultFromImport'](arg1, arg2, arg3, arg4);
}

export function DeleteVault(arg1) {
  return window['go']['main']['App']['DeleteVault'](arg1);
}

export function GetVault(arg1) {
  return window['go']['main']['App']['GetVault'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListVaults() {
  return window['go']['main']['App']['ListVaults']();
}

export function MinBackupPassphraseLength() {
  return window['go']['main']['App']['MinBackupPassphraseLength']();
}

export function RestoreVaults(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreVaults'](arg1, arg2, arg3);
}

export function StartupError() {
  return window['go']['main']['App']['StartupError']();
}

export function UpdateVault(arg1) {
  return window['go']['main']['App']['UpdateVault'](arg1);
}
