// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vault} from '../models';

export function ChooseVaultIcon():Promise<string>;

export function CreateVault(arg1:string,arg2:string):Promise<vault.Vault>;

export function DeleteVault(arg1:string):Promise<void>;

export function GetVault(arg1:string):Promise<vault.Vault>;

export function Greet(arg1:string):Promise<string>;

export function ListVaults():Promise<Array<vault.Vault>>;

export function UpdateVault(arg1:vault.Vault):Promise<void>;
